### ISSUE TITLE
Is it possible to highlight the selected string? 

### ISSUE THREAD

**Issue by you-n-g** [pevhall/simple_highlighting#3]
Hi,
I've some text like this 
```
Method - [Tid: 2, Mid: 1, MethodName: test.LockFreeList.add RW]
```

I want to highlight `add RW`.

Is it possible to highlight this?

I think it will be great if `<Plug>HighlightWordUnderCursor` could highlight selected content in Visual mode.

Thanks!

**Comment by pevhall** [comment]
Yes this is a good idea. It will take a little bit of doing. I'll look at
it on the weekend.

**Comment by pevhall** [comment]
Hi you-n-g,

I think it is working well enough now. Not flawlessly but should be useful 99% of the time. I'll leave the ticket open until you confirm that it is working for you.

**Comment by you-n-g** [comment]
@pevhall  Thanks so much! 
I test it just now.  It seems the selected last words will not be selected  https://terminalizer.com/view/914e01974328

Here is my customized config.
```
nmap <Leader>H <Plug>HighlightWordUnderCursor
vmap <Leader>H <Plug>HighlightWordUnderCursor
```

**Comment by pevhall** [comment]
So it looks like your expecting the last character to be selected with the rest of the text.

So I don't know how to do a video. But when I enter visual mode my cursor becomes a vertical line instead of a block. In this mode you can see that the last letter is actually not selected, with your cursor it looks like the last letter is selected when in fact I think it is not.

I think that the way it behaves at the moment might be correct. Try yanking or deleting some text from the visual selection, and see if it matches what the key-bind is highlighting. 

Thanks for your help in testing you-n-g

(edit spelling)

**Comment by you-n-g** [comment]
@you-n-g 
https://terminalizer.com/view/d58ca3364329
I try to delete in visual mode.  The last charactor is deleted.
But it is not when I want to highlight it.

**Comment by pevhall** [comment]
Thanks @you-n-g. Unfortunately both our vim applications seem to be behaving differently. Yours feel more correct so I have change it to the way which should work for you.

However I will need to modify it again later to get it working properly for both you setup and mine. I'll look into that next week.

But for the time being can you please test it again to see if it is working as you expect now.

**Comment by you-n-g** [comment]
@pevhall  Thanks so much. It works perfectly in my neovim now.

**Comment by pevhall** [comment]
Appears to be all fixed now
